### ISSUE TITLE
Create Product View

### ISSUE THREAD

**Issue by whitneycormack** [TemporaryOysters/bangazon-api#11]
- create Products view
- will allow users to add their products to inventory
- name, description, price, product type id (category)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by markellisdev** [comment]
Thanks for reviewing Trent!
