### ISSUE TITLE
Create Users Model

### ISSUE THREAD

**Issue by whitneycormack** [TemporaryOysters/bangazon-api#17]
- create Users model:
--creates Customer ID
--first name
--last name
--street address
--city
--state
--country
--sign up date
--payment type ID (if applicable)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by ghost** [comment]
Django's User model docs: https://docs.djangoproject.com/en/1.10/ref/contrib/auth/

To delete ```User``` on ```models.py```(?)  and make changes to custom fields on UserSerializer.  

Adding ```models.User``` required fields: ```username```, ```password```

Adding ```email``` field to serializer.  

Attributes to consider: ```name_validator```, ```is_authenticated```
