### ISSUE TITLE
Create BangOrder Serializer

### ISSUE THREAD

**Issue by whitneycormack** [TemporaryOysters/bangazon-api#23]
Create an individual serializer file for Order model
Format will be bangOrderSerializer.py

# Expected Behavior

Serializer should contain the following functions

# Current Behavior

None yet

which you can find here http://www.django-rest-framework.org/tutorial/1-serialization/

## Context

This is to convert models into a readable json format (serialization)

## Your Environment

* Link to your project: https://github.com/TemporaryOysters/bangazon-api

**Comment by TrentHand** [comment]
Check ma kode, oysters!
